---
# SPDX-License-Identifier: GPL-3.0-or-later

# Firewall final
#
# This task will deploy nftables.conf with all the sets, flush all chains if
# necessary and reload nftables. This enforces the final state of firewall, but
# no set is updated as other tasks themselves are expected to update the set
# elements.
########################################################
- name: Firewall Task 1 - Check if xcplane table exists
  ansible.builtin.command: nft list table inet xcplane
  register: xcplane_table
  changed_when: false
  failed_when: false
########################################################
- name: Firewall Task 2 - Deploy final nftables.conf
  ansible.builtin.template:
    src: "{{ configs_path }}/nft/nftables.conf"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
    validate: nft --check -f %s
########################################################
- name: Firewall Task 3 - Flush rules if xcplane table exits
  ansible.builtin.command: nft -f /etc/nftables.d/flush-rules.nft
  when: xcplane_table.rc == 0
  changed_when: xcplane_table.rc == 0
########################################################
# Ansible starts the unit with 'reloaded' if it is stopped
- name: Firewall Task 4 - Reload nftables systemd service
  ansible.builtin.systemd_service:
    state: reloaded
    name: nftables
########################################################
