---
# SPDX-License-Identifier: GPL-3.0-or-later

##########################################################
- name: Restart x-ui
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: false
    name: x-ui
##########################################################
