[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 4

backend = systemd
banaction = nftables
banaction_allports = nftables[type=allports]

ignoreip = 127.0.0.1/8 ::1

bantime.increment = true
bantime.factor = 2
bantime.max = 6w
