# Tying to access any path not whitelisted here will be considered trespassing.
[Definition]

failregex =
    ^<HOST> - .*"(?:GET|POST|HEAD|OPTIONS|DELETE) (?!/(?:$|{{ allowed_paths | join('|') }})(?:[/? ]|$)).* HTTP/.*" 404

ignoreregex =
