# Nginx doesn't serve such requests and the offender will be severely punished.

[Definition]

failregex = ^<HOST> - .*"(?:CONNECT|TRACE|TRACK|PROPFIND|MKCOL|MOVE|COPY|SEARCH|LOCK|UNLOCK|BPROPFIND)\s

ignoreregex =