# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
#include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

server:
    # can be uncommented if you do not need user privilege protection
    username: "unbound"

    # can be uncommented if you do not need file access protection
    chroot: ""

    # location of the trust anchor file that enables DNSSEC. note that
    # the location of this file can be elsewhere
    auto-trust-anchor-file: "/var/lib/unbound/root.key"

    # send minimal amount of information to upstream servers to enhance privacy
    qname-minimisation: yes
    # use-syslog: no
    hide-identity: yes
    hide-version: yes

    # keep frequently used records warm
    prefetch: yes

    # interface: 127.0.0.1@53 # no plain DNS queries
    # port: 53
    interface: 127.0.0.1@{{ unbound_https_port }}
    interface: ::1@{{ unbound_https_port }}
    https-port: {{ unbound_https_port }}
    http-endpoint: /{{ secrets.doh_endpoint }}

    # we let nginx have the reverse proxy
    http-notls-downstream: yes

remote-control:
    control-enable: no
    # by default the control interface is is 127.0.0.1 and ::1 and port 8953
    # it is possible to use a unix socket too
    control-interface: /run/unbound.ctl
