// SPDX-License-Identifier: GPL-3.0-or-later

use async_compression::tokio::bufread::GzipDecoder;
use chrono::Utc;
use csv::ReaderBuilder;
use futures_util::TryStreamExt;
use isocountry::CountryCode;
use reqwest;
use serde::Deserialize;
use std::collections::HashMap;
use std::fmt;
use std::io::Cursor;
use std::iter;
use std::net::IpAddr;
use std::path::PathBuf;
use std::sync::Arc;
use strum_macros::{AsRefStr, Display};
use tokio::fs;
use tokio::io::{AsyncReadExt, BufReader};
use tokio_rusqlite::{Connection as SqlConn, Error as SqlErr, params, rusqlite};
use tokio_util::io::StreamReader;
use tracing::info;

use crate::ansible::AnsibleAction;
use crate::constants::GEOIP_DB;
use crate::db::ToSqlError;
use crate::types::{BoxError, KetServer, WorkSpace};

/// Both NftChain and NftSet have the trait of writing their rules
pub trait NftRule {
    fn write_rule(
        self,
        workspace: &WorkSpace,
        server: &KetServer,
    ) -> impl std::future::Future<Output = Result<PathBuf, BoxError>> + Send;
}

/// An enum containing different nftables sets
pub enum NftSet {
    /// Builds the transient nft rule when changing SSH port. At this transient
    /// stage both ansible_port and ssh_port are opened before/during
    /// reconciliation.
    SshPre { server: Arc<KetServer> },

    /// Builds the final SSH nft rule post transition which allows incoming
    /// connection only to ssh_port.
    SshPost { server: Arc<KetServer> },

    /// The set that is used in the inbound rule which allows incoming
    /// connection to the inbounds' ports of a server
    Inbound { server: Arc<KetServer> },

    /// Builds the set for the IPv4 nft rule outblocked4 that blocks new
    /// outbound connection to the list of countries defined for the server in
    /// the cloud config
    OutBlocked4 {
        workspace: Arc<WorkSpace>,
        countries: Vec<CountryCode>,
    },

    /// Builds the set for the IPv6 nft rule outblocked6 that blocks new
    /// outbound connection to the list of countries defined for the server in
    /// the cloud config
    OutBlocked6 {
        workspace: Arc<WorkSpace>,
        countries: Vec<CountryCode>,
    },

    /// The Cloudflare IPv4 set
    Cloudflare4,
    /// The Cloudflare IPv6 set
    Cloudflare6,
}

/// Represents the three major nft chains
#[derive(Display, AsRefStr, Debug, Clone)]
#[strum(serialize_all = "lowercase")]
pub enum NftChain {
    Input,
    Output,
    Forward,
}

///////////////////////////////////////////////////////////////////
// ============================================================= //
///////////////////////////////////////////////////////////////////

impl fmt::Display for NftSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            NftSet::Cloudflare4 => write!(f, "cloudflare4"),
            NftSet::Cloudflare6 => write!(f, "cloudflare6"),
            NftSet::Inbound { .. } => write!(f, "inbound"),
            NftSet::SshPre { .. } => write!(f, "sshpre"),
            NftSet::SshPost { .. } => write!(f, "sshpost"),
            NftSet::OutBlocked4 { .. } => write!(f, "outblocked4"),
            NftSet::OutBlocked6 { .. } => write!(f, "outblocked6"),
        }
    }
}

impl NftRule for NftSet {
    /// Writes an nft rule for a set operation to disk
    async fn write_rule(
        self,
        workspace: &WorkSpace,
        server: &KetServer,
    ) -> Result<PathBuf, BoxError> {
        let rule_filename = format!("{}/{}.nft", server.name, &self);

        let rule = match self {
            NftSet::Cloudflare4 | NftSet::Cloudflare6 => {
                generate_cloudflare_elements(&self).await?
            }

            NftSet::OutBlocked4 { .. } | NftSet::OutBlocked6 { .. } => {
                generate_blocked_elements(self).await?
            }

            NftSet::SshPre { .. } | NftSet::SshPost { .. } => generate_ssh_rule(&self)?,

            NftSet::Inbound { .. } => generate_inbound_rule(&self)?,
        };

        let rule_path = workspace.dirs.data_dir.join(rule_filename);
        // The server directories might not have been created yet
        if let Some(parent) = rule_path.parent() {
            fs::create_dir_all(parent).await?;
        }

        fs::write(&rule_path, rule).await?;

        Ok(rule_path)
    }
}

impl NftRule for NftChain {
    /// Writes the nft rule for a chain operation
    async fn write_rule(
        self,
        workspace: &WorkSpace,
        server: &KetServer,
    ) -> Result<PathBuf, BoxError> {
        let rule = format!(
            "#!/usr/sbin/nft -f\n\n\
	     # Generated by xcplane\n\
	     # Chain: {}\n\
	     # Updated: {}\n\n\
	     flush chain inet xcplane {}",
            self,
            Utc::now().format("%Y-%m-%d_%H-%M-%S"),
            self,
        );

        let rule_filename = format!("{}/{}.nft", server.name, self);

        let rule_path = workspace.dirs.data_dir.join(rule_filename);
        // The server directories might not have been created yet
        if let Some(parent) = rule_path.parent() {
            fs::create_dir_all(parent).await?;
        }

        fs::write(&rule_path, rule).await?;

        Ok(rule_path)
    }
}
// =============================================================
/// Takes IPs or a range of IPs in the form of a string element and creates the
/// expression needed for constructing an nft rule
fn set_rule_gen(rule_name: String, elements: String) -> String {
    format!(
        "#!/usr/sbin/nft -f\n\n\
	 # Generated by xcplane\n\
	 # Set: {}\n\
	 # Updated: {}\n\n\
	 flush set inet xcplane {}\n\n\
	 add element inet xcplane {} {{\n    {}\n}}",
        rule_name,
        Utc::now().format("%Y-%m-%d_%H-%M-%S"),
        rule_name,
        rule_name,
        elements
    )
}
// =============================================================
/// Generates a transient [`NftSet::SshPre`] or a final [`NftSet::SshPost`] nft
/// rule for SSH
fn generate_ssh_rule(nftset: &NftSet) -> Result<String, BoxError> {
    let elements: Result<String, BoxError> = match nftset {
        NftSet::SshPre { server } => {
            let ansible_conn = server
                .ansible_conn
                .load_full()
                .ok_or("Couldn't unwrap AnsibleConn in generate_ssh_rule.")?;
            let ansible_port = ansible_conn.ansible_port.ok_or::<BoxError>(
                format!("ansible_port is absent from server {}", server.name).into(),
            )?;

            if ansible_port != server.ssh_port {
                Ok(ansible_port.to_string() + "," + &server.ssh_port.to_string())
            } else {
                Ok(ansible_port.to_string())
            }
        }

        NftSet::SshPost { server } => Ok(server.ssh_port.to_string()),
        _ => Err("Non-matching NftSet in generate_ssh_elements".into()),
    };
    // SshPre & SshPost both are SSH sets, so the rule_name is always "ssh"
    let rule = set_rule_gen("ssh".to_string(), elements?);
    Ok(rule)
}
// =============================================================
/// Creates an nft rule for inbound set which allows incoming connection to a
/// server's inbounds' ports
fn generate_inbound_rule(nftset: &NftSet) -> Result<String, BoxError> {
    let elements: Result<String, BoxError> = match nftset {
        NftSet::Inbound { server } => Ok(server
            .inbounds
            .iter()
            .filter_map(|inb| {
                // Excluding the super inbound
                if inb.port == 0 {
                    None
                } else {
                    Some(inb.port.to_string())
                }
            })
            .collect::<Vec<String>>()
            .join(",")),

        _ => Err("Non-matching NftSet in generate_inbound_elements".into()),
    };

    let rule = set_rule_gen(nftset.to_string(), elements?);
    Ok(rule)
}
// =============================================================
/// Downloads Cloudflare IPv4 or IPv6 ranges and creates a corresponding nft
/// rule
async fn generate_cloudflare_elements(nftset: &NftSet) -> Result<String, BoxError> {
    let elements: Result<String, BoxError> = match nftset {
        NftSet::Cloudflare4 => {
            let cf_ranges4 = reqwest::get("https://www.cloudflare.com/ips-v4/#")
                .await?
                .error_for_status()?
                .text()
                .await?;

            let cf_vec4 = cf_ranges4
                .lines()
                .map(|s| s.to_owned())
                .collect::<Vec<String>>();

            Ok(cf_vec4.join(",\n    "))
        }

        NftSet::Cloudflare6 => {
            let cf_ranges6 = reqwest::get("https://www.cloudflare.com/ips-v6/#")
                .await?
                .error_for_status()?
                .text()
                .await?;

            let cf_vec6 = cf_ranges6
                .lines()
                .map(|s| s.to_owned())
                .collect::<Vec<String>>();

            Ok(cf_vec6.join(",\n    "))
        }

        _ => Err("Non-matching NftSet in generate_cloudflare_elements".into()),
    };

    let rule = set_rule_gen(nftset.to_string(), elements?);
    Ok(rule)
}
// =============================================================
/// Creates an nft rule which blocks new outbound connections to the list of
/// countries set in the cloud
async fn generate_blocked_elements(nftset: NftSet) -> Result<String, BoxError> {
    // Since the DB is recreated periodically, reusing an SqlConn is not correct
    // and we needed to reopen the DB
    let rule_name = nftset.to_string();

    let elements: Result<String, BoxError> = match nftset {
        NftSet::OutBlocked4 {
            workspace,
            countries,
        } => {
            let db_file = workspace.dirs.data_dir.join(GEOIP_DB);
            let conn = SqlConn::open(&db_file).await?;

            let sql_holder = iter::repeat("?")
                .take(countries.len())
                .collect::<Vec<_>>()
                .join(",");

            let countries_str = countries.into_iter().map(|c| c.alpha2());

            let elements = conn
                .call(move |conn| {
                    let mut stmt4 = conn.prepare(&format!(
                        "SELECT start, end FROM geoip4 WHERE country IN ({})",
                        sql_holder
                    ))?;

                    let ip4_ranges_res = stmt4.query_map(
                        rusqlite::params_from_iter(countries_str.to_owned()),
                        |row| {
                            let start: String = row.get("start")?;
                            let end: String = row.get("end")?;

                            Ok(start + "-" + &end)
                        },
                    )?;

                    let mut ip4_ranges = Vec::new();

                    for ip_range in ip4_ranges_res {
                        ip4_ranges.push(ip_range?);
                    }

                    Ok::<_, SqlErr>(ip4_ranges.join(",\n    "))
                })
                .await?;

            Ok(elements)
        }
        //////////////////////////////////////////////////////
        NftSet::OutBlocked6 {
            workspace,
            countries,
        } => {
            let db_file = workspace.dirs.data_dir.join(GEOIP_DB);
            let conn = SqlConn::open(&db_file).await?;

            let sql_holder = iter::repeat("?")
                .take(countries.len())
                .collect::<Vec<_>>()
                .join(",");

            let countries_str = countries.into_iter().map(|c| c.alpha2());

            let elements = conn
                .call(move |conn| {
                    let mut stmt6 = conn.prepare(&format!(
                        "SELECT start, end FROM geoip6 WHERE country IN ({})",
                        sql_holder
                    ))?;

                    let ip6_ranges_res =
                        stmt6.query_map(rusqlite::params_from_iter(countries_str), |row| {
                            let start: String = row.get("start")?;
                            let end: String = row.get("end")?;

                            Ok(start + "-" + &end)
                        })?;

                    let mut ip6_ranges = Vec::new();

                    for ip_range in ip6_ranges_res {
                        ip6_ranges.push(ip_range?);
                    }

                    Ok::<_, SqlErr>(ip6_ranges.join(",\n    "))
                })
                .await?;

            Ok(elements)
        }

        _ => Err("Non-matching NftSet in generate_blocked_elements".into()),
    };

    let rule = set_rule_gen(rule_name, elements?);
    Ok(rule)
}
// =============================================================
/// Creates GeoIP v4/v6 database from the raw bytes of a CSV list
pub async fn create_geoip_db(workspace: &WorkSpace, data: Vec<u8>) -> Result<(), BoxError> {
    #[derive(Deserialize)]
    struct Record {
        start: String,
        end: String,
        country: String,
    }

    let db_file = workspace.dirs.data_dir.join(GEOIP_DB);
    // Delete the old DB first. Because a re-population of DB doesn't take much
    // less than completely recreating the tables, we always rebuild the DB. It
    // will also help to avoid conflicts, stales and duplicates.
    if db_file.exists() {
        // Using std lib provides a faster deletion than tokio::fs in this case
        std::fs::remove_file(&db_file)?;
    }

    let conn = Arc::new(SqlConn::open(&db_file).await?);

    // Wrap the byte buffer in a Cursor to implement std::io::Read
    let cursor = Cursor::new(data);

    // Let the CSV engine read it
    let mut reader = ReaderBuilder::new().has_headers(false).from_reader(cursor);

    conn.clone()
        .call(move |conn| {
            // Performance optimization
            conn.execute_batch(
                "
             PRAGMA journal_mode = MEMORY;
             PRAGMA synchronous = OFF;
             PRAGMA temp_store = MEMORY;
            ",
            )?;
            // Wrapping all the transactions in one commit brings even more
            // performance uplift
            let tx = conn.transaction()?;

            tx.execute_batch(
                "
             CREATE TABLE geoip4 (
		 start   TEXT,
		 end     TEXT,
                 country TEXT NOT NULL,
                 PRIMARY KEY(start, end)
             );

             CREATE TABLE geoip6 (
		 start   TEXT,
		 end     TEXT,
                 country TEXT NOT NULL,
                 PRIMARY KEY(start, end)
             );
             ",
            )?;

            let mut stmt4 = tx.prepare(
                "
             INSERT INTO geoip4 (start, end, country)
             VALUES (?1, ?2, ?3)
             ON CONFLICT(start, end) DO NOTHING
             ",
            )?;

            let mut stmt6 = tx.prepare(
                "
             INSERT INTO geoip6 (start, end, country)
             VALUES (?1, ?2, ?3)
             ON CONFLICT(start, end) DO NOTHING
             ",
            )?;

            for result in reader.deserialize() {
                let record: Record = result.to_sql_err()?;

                match (
                    record.start.parse::<IpAddr>().to_sql_err()?,
                    record.end.parse::<IpAddr>().to_sql_err()?,
                ) {
                    (IpAddr::V4(_), IpAddr::V4(_)) => {
                        stmt4.execute(params![record.start, record.end, record.country])?;
                    }
                    (IpAddr::V6(_), IpAddr::V6(_)) => {
                        stmt6.execute(params![record.start, record.end, record.country])?;
                    }
                    (_, _) => info!(
                        start = record.start,
                        end = record.end,
                        "skipping malformed start & end IPs",
                    ),
                }
            }

            // Creating an index in both tables to make queries faster
            tx.execute_batch(
                "
             CREATE INDEX indx4 ON geoip4(country);
             CREATE INDEX indx6 ON geoip6(country);
             ",
            )?;
            drop(stmt4);
            drop(stmt6);

            tx.commit()?;

            Ok::<_, SqlErr>(())
        })
        .await?;

    Ok(())
}
// =============================================================
/// Downloads the lite GeoIP compressed data from db-ip.com and converts it to a
/// vector of bytes
pub async fn dl_geoip_data() -> Result<Vec<u8>, BoxError> {
    let url = format!(
        "https://download.db-ip.com/free/dbip-country-lite-{}.csv.gz",
        Utc::now().format("%Y-%m")
    );

    let stream_resp = reqwest::get(url)
        .await?
        .error_for_status()?
        .bytes_stream()
        .map_err(std::io::Error::other);

    let reader_source = StreamReader::new(stream_resp);

    let reader = BufReader::new(reader_source);
    let mut decoder = GzipDecoder::new(reader);

    let mut buffer = Vec::new();
    decoder.read_to_end(&mut buffer).await?;

    Ok(buffer)
}
// =============================================================
/// This function prepares whatever nft rule operation needed by a group of
/// AnsibleAction's. Note that:
/// - Not every AnsibleAction needs an accompanying nft operation
/// - xcplane just generates nft operation files but does not directly apply
///   them. The required ones will be picked and used when running Ansible.
pub async fn generate_nftops(
    ansible_actions: &Vec<AnsibleAction>,
    workspace: Arc<WorkSpace>,
    server: Arc<KetServer>,
) -> Result<HashMap<String, PathBuf>, BoxError> {
    let mut ops = HashMap::<String, PathBuf>::new();

    for action in ansible_actions {
        match action {
            AnsibleAction::SSH => {
                let set1 = NftSet::SshPre {
                    server: server.clone(),
                };
                let set2 = NftSet::SshPost {
                    server: server.clone(),
                };
                ops.entry(set1.to_string())
                    .or_insert(set1.write_rule(&workspace, &server).await?);
                ops.entry(set2.to_string())
                    .or_insert(set2.write_rule(&workspace, &server).await?);
            }

            AnsibleAction::FullSetup => {
                let full_set = vec![
                    NftSet::Cloudflare4,
                    NftSet::Cloudflare6,
                    NftSet::OutBlocked4 {
                        workspace: workspace.clone(),
                        countries: server.outbound_block.clone(),
                    },
                    NftSet::OutBlocked6 {
                        workspace: workspace.clone(),
                        countries: server.outbound_block.clone(),
                    },
                    NftSet::Inbound {
                        server: server.clone(),
                    },
                    NftSet::SshPre {
                        server: server.clone(),
                    },
                    NftSet::SshPost {
                        server: server.clone(),
                    },
                ];

                for set in full_set {
                    ops.entry(set.to_string())
                        .or_insert(set.write_rule(&workspace, &server).await?);
                }
            }

            AnsibleAction::DelInbound | AnsibleAction::AddInbound => {
                let set = NftSet::Inbound {
                    server: server.clone(),
                };
                ops.entry(set.to_string())
                    .or_insert(set.write_rule(&workspace, &server).await?);
            }

            AnsibleAction::OutblockedUpdate => {
                let required_sets = vec![
                    NftSet::Cloudflare4,
                    NftSet::Cloudflare6,
                    NftSet::OutBlocked4 {
                        workspace: workspace.clone(),
                        countries: server.outbound_block.clone(),
                    },
                    NftSet::OutBlocked6 {
                        workspace: workspace.clone(),
                        countries: server.outbound_block.clone(),
                    },
                ];

                for set in required_sets {
                    ops.entry(set.to_string())
                        .or_insert(set.write_rule(&workspace, &server).await?);
                }
            }
            _ => {}
        }
    }

    Ok(ops)
}
// =============================================================
